# Generated by Django 4.0.5 on 2022-06-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='education',
            field=models.ManyToManyField(to='newapp.educationmodel'),
        ),
        migrations.AlterField(
            model_name='userinformations',
            name='experience',
            field=models.ManyToManyField(to='newapp.experiencemodel'),
        ),
    ]
