# Generated by Django 4.0.5 on 2022-06-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_userinformations_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='education',
            field=models.ManyToManyField(blank=True, to='newapp.educationmodel'),
        ),
        migrations.AlterField(
            model_name='userinformations',
            name='experience',
            field=models.ManyToManyField(blank=True, to='newapp.experiencemodel'),
        ),
        migrations.AlterField(
            model_name='userinformations',
            name='skills',
            field=models.ManyToManyField(blank=True, to='newapp.skillsmodel'),
        ),
    ]
