# Generated by Django 4.0.5 on 2022-06-09 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_userinformations_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformations',
            name='education',
        ),
        migrations.RemoveField(
            model_name='userinformations',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='userinformations',
            name='skills',
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='newapp.userinformations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='project_urls',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='newapp.userinformations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillsmodel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='newapp.userinformations'),
            preserve_default=False,
        ),
    ]
