# Generated by Django 4.0.5 on 2022-06-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_remove_userinformations_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencemodel',
            name='project_urls',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.userinformations'),
        ),
    ]
