# Generated by Django 4.0.5 on 2022-06-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_alter_experiencemodel_project_urls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='userinformations',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='newapp.skillsmodel'),
        ),
    ]
