# Generated by Django 4.0.5 on 2022-06-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_remove_skillsmodel_user_userinformations_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformations',
            name='profile_summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
