# Generated by Django 4.0.5 on 2022-06-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_userinformations_profile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformations',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
