# Generated by Django 4.0.5 on 2022-06-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_userinformations_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencemodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
