# Generated by Django 4.0.5 on 2022-06-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_alter_experiencemodel_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
