# Generated by Django 4.0.5 on 2022-06-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_alter_educationmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='degree',
            field=models.CharField(max_length=255),
        ),
    ]
